// <auto-generated />
using Ecommerce.Server.Controllers.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Ecommerce.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220302112643_1st create")]
    partial class _1stcreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Ecommerce.Shared.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "MIT’s new mini cheetah robot is springy and light on its feet, with a range of motion that rivals a champion gymnast. The four-legged powerpack can bend and swing its legs wide, enabling it to walk either right-side up or upside down. The robot can also trot over uneven terrain about twice as fast as an average person’s walking speed.",
                            ImageUrl = "https://robots.ieee.org/robots/minicheetah/minicheetah-thumb@2x.jpg",
                            Price = 100m,
                            Title = "Cheetah"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Spot is an agile mobile robot that navigates terrain with unprecedented mobility, allowing you to automate routine inspection tasks and data capture safely, accurately, and frequently. The results? Safer, more efficient and more predictable operations.",
                            ImageUrl = "https://static.wikia.nocookie.net/robotics/images/6/64/38AB8AB0-0E22-4200-A4A6-382335BEEC5E.jpeg",
                            Price = 111m,
                            Title = "Spot"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Atlas has one of the world’s most compact mobile hydraulic systems. A custom battery, valves, and a compact hydraulic power unit enable Atlas to deliver high power to any of its 28 hydraulic joints for impressive feats of mobility.",
                            ImageUrl = "https://i.pinimg.com/originals/d3/33/3f/d3333fc913a33c7d3bde8ee006dc1323.png",
                            Price = 299m,
                            Title = "Atlas"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
